apiVersion: apps/v1
kind: Deployment
metadata:
  name: petrosa-crypto-screenings
  namespace: petrosa-apps
  labels:
    app: petrosa-crypto-screenings-app
spec:
  selector:
    matchLabels:
      app: petrosa-crypto-screenings
  template:
    metadata:
      labels:
        app: petrosa-crypto-screenings
    spec:
      hostname: screenings
      subdomain: petrosa-screenings
      containers:
      - name: petrosa-crypto-screenings
        image: yurisa2/petrosa-crypto-screenings:v0.0.10
        imagePullPolicy: Always

        ports:
        - containerPort: 80
          name: http-web-svc

        env:
          - name: VERSION
            value: "0.0.10"
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: MONGO_URI
                optional: false
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: NEW_RELIC_LICENSE_KEY
                optional: false
          - name: KAFKA_SUBSCRIBER
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: KAFKA_SUBSCRIBER
                optional: false
          - name: BINANCE_API_KEY
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: BINANCE_API_KEY
                optional: false
          - name: BINANCE_API_SECRET
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: BINANCE_API_SECRET
                optional: false
          - name: BINANCE_ORDERS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: BINANCE_ORDERS_ENDPOINT
                optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-screenings-service
spec:
  selector:
    app: petrosa-crypto-screenings
  ports:
  - port: 80
    targetPort: 80
